# docker compose -f docker-infra.yml up -d
# docker compose -f docker-infra.yml down --remove-orphans

services:
  mongodb-curso-sn:
    image: mongo:8.0.3-noble
    container_name: mongodb-cursocn
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc12345678
    networks:
      - rede-net

  mongo-express-sn:
    image: mongo-express:1.0.2-20
    container_name: mongoexpress-cursocn
    restart: always
    depends_on:
      - mongodb-curso-sn
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_SERVER: mongodb-cursocn
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress-user
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress-pass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: 'dracula'
      ME_CONFIG_SITE_BASEURL: '/'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Abc12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:Abc12345678@mongodb-cursocn:27017/
    networks:
      - rede-net

networks:
  rede-net:
    driver: bridge
