# docker-compose -f docker-infra.yml up -d
# docker-compose -f docker-infra.yml down --remove-orphans

version: '3.8'

services:
  mongodb:
    image: mongo:7.0.7
    container_name: mongodb-curso
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc12345678
    networks:
      - rede-net

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express-curso
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress-user
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress-pass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
      ME_CONFIG_SITE_BASEURL: '/'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Abc12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:Abc12345678@mongodb-curso:27017/

networks:
  rede-net:
    driver: bridge
